name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    - cron: '42 5 * * *'

jobs:
  perl-tester:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.32'
          - '5.30'
          - '5.20'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester

    name: Build on Linux with Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
            perl -v
            #apt-get update
            apt-get install -y libreadline-dev

      - name: Regular tests
        env:
            RELEASE_TESTING: 1
        run: |
            cpanm --verbose Term::ReadLine::Gnu

  perl:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.32'
          - '5.30'
          - '5.20'

    container:
      image: perl:${{ matrix.perl-version }}

    name: Build on Linux with Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
            perl -v
            #apt-get update
            apt-get install -y libreadline-dev

      - name: Regular tests
        env:
            RELEASE_TESTING: 1
        run: |
            cpanm --verbose Term::ReadLine::Gnu


  plain-ubuntu:
    runs-on: ubuntu-latest
    #env:
    #  TERM: xterm-256color

    container:
      image: ubuntu:20.10

    name: Build on Ubuntu 20.10
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
            perl -v
            apt-get update
            apt-get install -y perl
            apt-get install -y libterm-readline-gnu-perl

      - name: Show version
        run: |
            perl -MTerm::ReadLine -e 'print "Term::ReadLine $Term::ReadLine::VERSION\n"'
            perl -MTerm::ReadLine -e 'print "Term::ReadLine::Gnu $Term::ReadLine::Gnu::VERSION\n"'


  plain-ubuntu-cpanm:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color

    container:
      image: ubuntu:20.10

    name: Build on Ubuntu 20.10
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
            perl -v
            apt-get update
            apt-get install -y perl
            apt-get install -y build-essential
            apt-get install -y curl
            apt-get install -y libncurses-dev
            apt-get install -y libreadline-dev

      - name: Regular tests
        env:
            RELEASE_TESTING: 1
        run: |
            curl -L https://cpanmin.us | perl - App::cpanminus
            cpanm --verbose Term::ReadLine::Gnu
      - name: Show version
        run: |
            perl -MTerm::ReadLine -e 'print "Term::ReadLine $Term::ReadLine::VERSION\n"'
            perl -MTerm::ReadLine -e 'print "Term::ReadLine::Gnu $Term::ReadLine::Gnu::VERSION\n"'


  plain-centos:
    runs-on: ubuntu-latest
    #env:
    #  TERM: xterm-256color
    strategy:
      fail-fast: false
      matrix:
        centos:
          - '7'
          - '8'


    container:
      image: centos:${{ matrix.centos }}

    name: Build on Centos ${{ matrix.centos }}
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
            yum install -y perl
            perl -V
            yum install -y epel-release
            yum install -y perl-Term-ReadLine-Gnu

      - name: Show version
        run: |
            perl -MTerm::ReadLine -e 'print "Term::ReadLine $Term::ReadLine::VERSION\n"'
            perl -MTerm::ReadLine -e 'print "Term::ReadLine::Gnu $Term::ReadLine::Gnu::VERSION\n"'


  ubuntu-native:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color

    name: Ubuntu native
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
            perl -v
            #apt-get update
            sudo apt-get install -y libreadline-dev

      - name: Install
        env:
            RELEASE_TESTING: 1
        run: |
            curl -L https://cpanmin.us | perl - App::cpanminus
            ~/perl5/bin/cpanm --verbose Term::ReadLine::Gnu

# TODO
  windows-native-strawberry:
    runs-on: windows-latest
    #env:
    #  TERM: xterm-256color

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.32'
          #- '5.30'
          #- '5.20'

    name: Windows native
    steps:
      - uses: actions/checkout@v2

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
            perl-version: ${{ matrix.perl }}
            distribution: 'strawberry'


      - name: Install prerequisites
        run: |
            perl -v
            #apt-get update
            #sudo apt-get install -y libreadline-dev

#      - name: Install
#        env:
#            RELEASE_TESTING: 1
#        run: |
#            #curl -L https://cpanmin.us | perl - App::cpanminus
#            cpanm --verbose Term::ReadLine::Gnu

